# app.yaml

runtime: python311
env: standard
entrypoint: gunicorn -b :$PORT PasswordManager.wsgi:application

handlers:
- url: /static              # new
  static_dir: static/  # new
- url: /media               # new
  static_dir: media/   # new
- url: /.*
  script: auto

runtime_config:
  python_version: 3